### ISSUE TITLE
The mountain shifted below the axis line 

### ISSUE THREAD

**Issue by k6Labz** [VS-work/gapminder-offline#33] opened 2017-01-16 12:50 UTC
**Steps To Reproduce:**

1. Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2. Click on mountain chart
3. Click on play to move slider to 1803
4. Click on show
5. Click on Afghanistan

![1-16-2017 5-43-29 pm](https://cloud.githubusercontent.com/assets/9950837/21983649/20a103d0-dc14-11e6-9ed0-072c7e14609f.jpg)

**Comment by angieskazka** [comment] 2017-01-26 18:23
duplicate of https://github.com/vizabi/vizabi/issues/2271
should be fixed in vizabi

**Closed by angieskazka** 2017-01-26 18:23 UTC

**Comment by k6Labz** [comment] 2017-01-27 13:01
not fixed
